import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "@/components/Navbar";
import { ReactLenis } from "@/utils/lenis";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
import Providers from "./providers";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hack MNC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ReactLenis root>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
        >
          <SessionProvider>
            <Providers>
              <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
                <Navbar />
                <main className="pt-20 min-h-screen flex items-center justify-center w-full sm:px-16">
                  {children}
                  <Toaster />
                </main>
                <Footer />
              </ThemeProvider>
            </Providers>
          </SessionProvider>
        </body>
      </ReactLenis>
    </html>
  );
}
